import { Box, Container, Divider, Grid, Typography } from "@mui/material";
import { useSession } from "next-auth/react";
import Head from "next/head";
import React from "react";
import { withAuth } from "../hocs";
import theme from "../src/theme";
import ProfileMenu from "./ProfileMenu";

interface IProps {
  title: string;
  logoUrl: string;
  logoAlt: string;
  menuLabel: string;
}

const Layout: React.FC<IProps> = ({ children, title, logoAlt, logoUrl, menuLabel }) => {
  const { data } = useSession();
  return (
    <div>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <Grid container paddingY={2}>
          <img src={logoUrl} alt={logoAlt} />
        </Grid>
        <Divider />
        <Grid container paddingY={1} justifyContent="space-between">
          <Grid item>
            <Typography variant="h6" fontWeight="normal" component="span" color={theme.palette.text.secondary}>
              {menuLabel}
            </Typography>
          </Grid>
          <Grid item>
            <ProfileMenu user={(data as any).user}  />
          </Grid>
        </Grid>
      </Container>
      <Divider />
      <Box marginBottom={2} />
      <Container>
        {children}
      </Container>
    </div>
  );
};

export default withAuth(Layout);
