import { Container, Grid, Typography } from "@mui/material";
import moment from 'moment';
import type { GetStaticPaths, GetStaticProps, NextPage } from "next";
import Head from "next/head";
import newsService, { INewsItem } from "../../lib/newsService";
import theme from "../../src/theme";

interface IProps {
  item: INewsItem;
}

const Item: NextPage<IProps> = ({ item }) => {
  return (
    <div>
      <Head>
        <title>{item.title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <Grid container spacing={2} marginY={1} key={item.id}>
          <Grid item sm={4} lg={3}>
            <img src={item.imageUrl} style={{ width: '100%' }} />
          </Grid>
          <Grid item sm={8} lg={9}>
            <Typography variant="subtitle1" component="h4" color={theme.palette.primary.main}>
              {item.topics}
            </Typography>
            <Typography variant="h5" component="h3">
              {item.title}
            </Typography>
            <Typography marginTop={2}>
              {item.description}
            </Typography>
            <Grid container spacing={1} columnSpacing={2} marginTop={1}>
              <Grid item color={theme.palette.text.secondary}>
                {moment(item.publicationDate).format('MMM DD, YYYY')}
              </Grid>
              <Grid item color={theme.palette.text.disabled}>|</Grid>
              <Grid item color={theme.palette.primary.main}>
                {item.author}
              </Grid>
            </Grid>
          </Grid>
        </Grid>
      </Container>
    </div>
  );
};

export const getStaticPaths: GetStaticPaths = async () => {
  const news = await newsService.getList();
  const paths = news.map(({ slug }) => ({ params: { slug } }));
  return {
    paths,
    fallback: true // false or 'blocking'
  };
}

export const getStaticProps: GetStaticProps = async ({ params }) => {
  if (params?.slug) {
    const item = await newsService.getBySlug(params.slug as string);
    return {
      props: { item }
    }
  }
  return {
    props: {}
  }
}

export default Item;
